version: '3.8'

services:
  robot-controller:
    build:
      context: .
      dockerfile: code/robot_ws/Dockerfile
    image: auto-dump-robot-runtime:humble
    container_name: auto_dump_robot
    privileged: true
    network_mode: "host"
    ipc: "host"
    stdin_open: true
    tty: true
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-83}
      ROS_LOCALHOST_ONLY: "0"
      BUILD_ON_START: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ./code/robot_ws/src:/root/ros2_ws/auto-dump-bot/code/robot_ws/src
    command: bash

  fastapi-backend:
    # build 설정을 context와 dockerfile 경로로 세부 지정
    build:
      context: ./code/backend
      dockerfile: Dockerfile
    container_name: autodump_backend

    network_mode: "host"
    # 호스트의 ROS 2 공유 메모리(IPC) 영역을 컨테이너와 직접 공유
    ipc: "host"
    
    # 볼륨 매핑도 백엔드 폴더에 맞게 수정
    volumes:
      - ./code/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=83 # 이거 각자 도메인 아이디로 하세요!!
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST # 환경변수 주입
    restart: always
